### PR TITLE
Add internship status for HPE

### PR DESCRIPTION
**Pull request by nisargshah95**

### CODE REVIEW

**Comment by shauryashekhar** [comment]
Acha.

**Comment by gcreddy42** [comment]
Thanks for the PR, @nisargshah95 . HP has already been updated.

**Comment by sarahbutt** [comment]
Curious, is this for HP or HPE?

**Comment by nisargshah95** [comment]
This is actually for HPE.

**Comment by gcreddy42** [comment]
Sorry @nisargshah95 , I got confused between HP and HPE. Merged now. Thanks for your contribution.

**Pull request merged**
